@host = http://localhost:5500

# Get all groups
GET {{host}}/groups

### 

# Get single group
GET {{host}}/groups/1

### 

# Create group
POST {{host}}/groups
Content-Type: application/json

{
  "name": "Bancolombia"
}

###

# Update
PUT {{host}}/groups/1
Content-Type: application/json

{
  "description": "Bancolombia description"
}


###

PATCH {{host}}/groups/1
Content-Type: application/json

{
  "name": "Another Bancolombia description"
}

###

# Delete group
DELETE {{host}}/groups/1

###

POST {{host}}/requests
Content-Type: application/json

{
  "body": "COFFEE"
}
